# Generated by Django 5.0.4 on 2024-11-25 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
